# Generated by Django 5.1.2 on 2024-11-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employee_bill_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBillProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('quantity', models.FloatField()),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee_bill_production',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='employee_bill_production',
        ),
    ]
