# Generated by Django 5.1.2 on 2024-11-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_employeebillproduction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMemoChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cashmemo_Challan',
                'managed': False,
            },
        ),
    ]
